
#  =====================================
#
#       █▄ ▄█ ▄▀▄ █▄ █ █ ▀█▀ ▄▀▄ █▀▄
#       █ ▀ █ ▀▄▀ █ ▀█ █  █  ▀▄▀ █▀▄
#
#  =====================================

#  (https://github.com/nwg-piotr/nwg-displays) cheat seet 
#  NOTE: requires "wlr-randr" pkg
#  list available Monitors with "hyprctl monitors"
#  monitor=name,resolution,position,scale

monitor=eDP-1,3072x1920@165,auto,1.6
monitor=HDMI-A-1,1920x1080@60,auto,1

# Set preferred monitors for workspaces
workspace = 0, monitor:eDP-1, default:true
workspace = 1, monitor:eDP-1 
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1
workspace = 6, monitor:eDP-1
workspace = 7, monitor:eDP-1
workspace = 8, monitor:eDP-1
workspace = 9, monitor:eDP-1
workspace = 10, monitor:HDMI-A-1, default:true
